services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    ErdmannFreunde\ContaoStatusUpdateBundle\EventListener\StatusUpdateSystemMessageListener:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@translator'

    ErdmannFreunde\ContaoStatusUpdateBundle\Mailer\NotificationMailer:
        arguments:
            - '@database_connection'
            - '@mailer'
            - '@contao.insert_tag.parser'
            - '@security.helper'
            - '@contao.framework'
            - '@translator'

    ErdmannFreunde\ContaoStatusUpdateBundle\EventListener\SendCompletionMailListener:
        arguments:
            - '@database_connection'
            - '@ErdmannFreunde\ContaoStatusUpdateBundle\Mailer\NotificationMailer'
